### ISSUE TITLE
center loss initialization

### ISSUE THREAD

**Issue by wb1997-cell** [i13abe/Adaptive-discriminant-and-center#1]
Hello, I have a question for you. The center function is initialized with everything set to 0,This does not seem to update the central location, Whether it's a normal central criterion or an adaptive central criterion.

**Comment by i13abe** [comment]
Hi @wb1997-cell !
Thank you for your comment.
The location of center is updated by computeCneter() function in utils/centerloss.py (or utils/adaptive_centerloss.py).
At 39 line (or 29 line) on utils/centerloss.py (or utils/adaptive_centerloss.py), self.center is updated '+= xxxxxx'.
It means that the center can be updated despite initial value of center.
But, your asking is very nice!
You can implement initializing of central location in __init__().
